version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3999:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8999:8086"  # expõe o backend para teste no host
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - app-network
    ports:
      - "4999:80"  # host:container
    depends_on:
      - backend


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
